// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: appointment.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/folucode/appointment-scheduler/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AppointmentServiceName is the fully-qualified name of the AppointmentService service.
	AppointmentServiceName = "appointment.AppointmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AppointmentServiceGetAppointmentProcedure is the fully-qualified name of the AppointmentService's
	// GetAppointment RPC.
	AppointmentServiceGetAppointmentProcedure = "/appointment.AppointmentService/GetAppointment"
	// AppointmentServiceGetUserAppointmentsProcedure is the fully-qualified name of the
	// AppointmentService's GetUserAppointments RPC.
	AppointmentServiceGetUserAppointmentsProcedure = "/appointment.AppointmentService/GetUserAppointments"
	// AppointmentServiceCreateAppointmentProcedure is the fully-qualified name of the
	// AppointmentService's CreateAppointment RPC.
	AppointmentServiceCreateAppointmentProcedure = "/appointment.AppointmentService/CreateAppointment"
	// AppointmentServiceUpdateAppointmentProcedure is the fully-qualified name of the
	// AppointmentService's UpdateAppointment RPC.
	AppointmentServiceUpdateAppointmentProcedure = "/appointment.AppointmentService/UpdateAppointment"
	// AppointmentServiceDeleteAppointmentProcedure is the fully-qualified name of the
	// AppointmentService's DeleteAppointment RPC.
	AppointmentServiceDeleteAppointmentProcedure = "/appointment.AppointmentService/DeleteAppointment"
)

// AppointmentServiceClient is a client for the appointment.AppointmentService service.
type AppointmentServiceClient interface {
	GetAppointment(context.Context, *connect.Request[proto.GetAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	GetUserAppointments(context.Context, *connect.Request[proto.GetUserAppointmentRequest]) (*connect.Response[proto.GetUserAppointmentResponse], error)
	CreateAppointment(context.Context, *connect.Request[proto.CreateAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	UpdateAppointment(context.Context, *connect.Request[proto.UpdateAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	DeleteAppointment(context.Context, *connect.Request[proto.DeleteAppointmentRequest]) (*connect.Response[proto.DeleteAppointmentResponse], error)
}

// NewAppointmentServiceClient constructs a client for the appointment.AppointmentService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppointmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AppointmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	appointmentServiceMethods := proto.File_appointment_proto.Services().ByName("AppointmentService").Methods()
	return &appointmentServiceClient{
		getAppointment: connect.NewClient[proto.GetAppointmentRequest, proto.Appointment](
			httpClient,
			baseURL+AppointmentServiceGetAppointmentProcedure,
			connect.WithSchema(appointmentServiceMethods.ByName("GetAppointment")),
			connect.WithClientOptions(opts...),
		),
		getUserAppointments: connect.NewClient[proto.GetUserAppointmentRequest, proto.GetUserAppointmentResponse](
			httpClient,
			baseURL+AppointmentServiceGetUserAppointmentsProcedure,
			connect.WithSchema(appointmentServiceMethods.ByName("GetUserAppointments")),
			connect.WithClientOptions(opts...),
		),
		createAppointment: connect.NewClient[proto.CreateAppointmentRequest, proto.Appointment](
			httpClient,
			baseURL+AppointmentServiceCreateAppointmentProcedure,
			connect.WithSchema(appointmentServiceMethods.ByName("CreateAppointment")),
			connect.WithClientOptions(opts...),
		),
		updateAppointment: connect.NewClient[proto.UpdateAppointmentRequest, proto.Appointment](
			httpClient,
			baseURL+AppointmentServiceUpdateAppointmentProcedure,
			connect.WithSchema(appointmentServiceMethods.ByName("UpdateAppointment")),
			connect.WithClientOptions(opts...),
		),
		deleteAppointment: connect.NewClient[proto.DeleteAppointmentRequest, proto.DeleteAppointmentResponse](
			httpClient,
			baseURL+AppointmentServiceDeleteAppointmentProcedure,
			connect.WithSchema(appointmentServiceMethods.ByName("DeleteAppointment")),
			connect.WithClientOptions(opts...),
		),
	}
}

// appointmentServiceClient implements AppointmentServiceClient.
type appointmentServiceClient struct {
	getAppointment      *connect.Client[proto.GetAppointmentRequest, proto.Appointment]
	getUserAppointments *connect.Client[proto.GetUserAppointmentRequest, proto.GetUserAppointmentResponse]
	createAppointment   *connect.Client[proto.CreateAppointmentRequest, proto.Appointment]
	updateAppointment   *connect.Client[proto.UpdateAppointmentRequest, proto.Appointment]
	deleteAppointment   *connect.Client[proto.DeleteAppointmentRequest, proto.DeleteAppointmentResponse]
}

// GetAppointment calls appointment.AppointmentService.GetAppointment.
func (c *appointmentServiceClient) GetAppointment(ctx context.Context, req *connect.Request[proto.GetAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return c.getAppointment.CallUnary(ctx, req)
}

// GetUserAppointments calls appointment.AppointmentService.GetUserAppointments.
func (c *appointmentServiceClient) GetUserAppointments(ctx context.Context, req *connect.Request[proto.GetUserAppointmentRequest]) (*connect.Response[proto.GetUserAppointmentResponse], error) {
	return c.getUserAppointments.CallUnary(ctx, req)
}

// CreateAppointment calls appointment.AppointmentService.CreateAppointment.
func (c *appointmentServiceClient) CreateAppointment(ctx context.Context, req *connect.Request[proto.CreateAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return c.createAppointment.CallUnary(ctx, req)
}

// UpdateAppointment calls appointment.AppointmentService.UpdateAppointment.
func (c *appointmentServiceClient) UpdateAppointment(ctx context.Context, req *connect.Request[proto.UpdateAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return c.updateAppointment.CallUnary(ctx, req)
}

// DeleteAppointment calls appointment.AppointmentService.DeleteAppointment.
func (c *appointmentServiceClient) DeleteAppointment(ctx context.Context, req *connect.Request[proto.DeleteAppointmentRequest]) (*connect.Response[proto.DeleteAppointmentResponse], error) {
	return c.deleteAppointment.CallUnary(ctx, req)
}

// AppointmentServiceHandler is an implementation of the appointment.AppointmentService service.
type AppointmentServiceHandler interface {
	GetAppointment(context.Context, *connect.Request[proto.GetAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	GetUserAppointments(context.Context, *connect.Request[proto.GetUserAppointmentRequest]) (*connect.Response[proto.GetUserAppointmentResponse], error)
	CreateAppointment(context.Context, *connect.Request[proto.CreateAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	UpdateAppointment(context.Context, *connect.Request[proto.UpdateAppointmentRequest]) (*connect.Response[proto.Appointment], error)
	DeleteAppointment(context.Context, *connect.Request[proto.DeleteAppointmentRequest]) (*connect.Response[proto.DeleteAppointmentResponse], error)
}

// NewAppointmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppointmentServiceHandler(svc AppointmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	appointmentServiceMethods := proto.File_appointment_proto.Services().ByName("AppointmentService").Methods()
	appointmentServiceGetAppointmentHandler := connect.NewUnaryHandler(
		AppointmentServiceGetAppointmentProcedure,
		svc.GetAppointment,
		connect.WithSchema(appointmentServiceMethods.ByName("GetAppointment")),
		connect.WithHandlerOptions(opts...),
	)
	appointmentServiceGetUserAppointmentsHandler := connect.NewUnaryHandler(
		AppointmentServiceGetUserAppointmentsProcedure,
		svc.GetUserAppointments,
		connect.WithSchema(appointmentServiceMethods.ByName("GetUserAppointments")),
		connect.WithHandlerOptions(opts...),
	)
	appointmentServiceCreateAppointmentHandler := connect.NewUnaryHandler(
		AppointmentServiceCreateAppointmentProcedure,
		svc.CreateAppointment,
		connect.WithSchema(appointmentServiceMethods.ByName("CreateAppointment")),
		connect.WithHandlerOptions(opts...),
	)
	appointmentServiceUpdateAppointmentHandler := connect.NewUnaryHandler(
		AppointmentServiceUpdateAppointmentProcedure,
		svc.UpdateAppointment,
		connect.WithSchema(appointmentServiceMethods.ByName("UpdateAppointment")),
		connect.WithHandlerOptions(opts...),
	)
	appointmentServiceDeleteAppointmentHandler := connect.NewUnaryHandler(
		AppointmentServiceDeleteAppointmentProcedure,
		svc.DeleteAppointment,
		connect.WithSchema(appointmentServiceMethods.ByName("DeleteAppointment")),
		connect.WithHandlerOptions(opts...),
	)
	return "/appointment.AppointmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AppointmentServiceGetAppointmentProcedure:
			appointmentServiceGetAppointmentHandler.ServeHTTP(w, r)
		case AppointmentServiceGetUserAppointmentsProcedure:
			appointmentServiceGetUserAppointmentsHandler.ServeHTTP(w, r)
		case AppointmentServiceCreateAppointmentProcedure:
			appointmentServiceCreateAppointmentHandler.ServeHTTP(w, r)
		case AppointmentServiceUpdateAppointmentProcedure:
			appointmentServiceUpdateAppointmentHandler.ServeHTTP(w, r)
		case AppointmentServiceDeleteAppointmentProcedure:
			appointmentServiceDeleteAppointmentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAppointmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppointmentServiceHandler struct{}

func (UnimplementedAppointmentServiceHandler) GetAppointment(context.Context, *connect.Request[proto.GetAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("appointment.AppointmentService.GetAppointment is not implemented"))
}

func (UnimplementedAppointmentServiceHandler) GetUserAppointments(context.Context, *connect.Request[proto.GetUserAppointmentRequest]) (*connect.Response[proto.GetUserAppointmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("appointment.AppointmentService.GetUserAppointments is not implemented"))
}

func (UnimplementedAppointmentServiceHandler) CreateAppointment(context.Context, *connect.Request[proto.CreateAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("appointment.AppointmentService.CreateAppointment is not implemented"))
}

func (UnimplementedAppointmentServiceHandler) UpdateAppointment(context.Context, *connect.Request[proto.UpdateAppointmentRequest]) (*connect.Response[proto.Appointment], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("appointment.AppointmentService.UpdateAppointment is not implemented"))
}

func (UnimplementedAppointmentServiceHandler) DeleteAppointment(context.Context, *connect.Request[proto.DeleteAppointmentRequest]) (*connect.Response[proto.DeleteAppointmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("appointment.AppointmentService.DeleteAppointment is not implemented"))
}
