ALTER TABLE appointments
DROP COLUMN IF EXISTS user_id;

ALTER TABLE appointments
ADD COLUMN user_id UUID NOT NULL;

ALTER TABLE appointments
ADD CONSTRAINT fk_user
FOREIGN KEY (user_id) REFERENCES users(id);


ALTER TABLE appointments
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

ALTER TABLE appointments
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
