// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: appointment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ContactInformation *ContactInformation    `protobuf:"bytes,4,opt,name=contact_information,json=contactInformation,proto3" json:"contact_information,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Title              string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Date               *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Appointment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Appointment) GetContactInformation() *ContactInformation {
	if x != nil {
		return x.ContactInformation
	}
	return nil
}

func (x *Appointment) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Appointment) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Appointment) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAppointmentRequest) Reset() {
	*x = GetUserAppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAppointmentRequest) ProtoMessage() {}

func (x *GetUserAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetUserAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserAppointmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointments  []*Appointment         `protobuf:"bytes,1,rep,name=appointments,proto3" json:"appointments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAppointmentResponse) Reset() {
	*x = GetUserAppointmentResponse{}
	mi := &file_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAppointmentResponse) ProtoMessage() {}

func (x *GetUserAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetUserAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserAppointmentResponse) GetAppointments() []*Appointment {
	if x != nil {
		return x.Appointments
	}
	return nil
}

type CreateAppointmentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactInformation *ContactInformation    `protobuf:"bytes,2,opt,name=contact_information,json=contactInformation,proto3" json:"contact_information,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Description        string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Title              string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Date               *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAppointmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetContactInformation() *ContactInformation {
	if x != nil {
		return x.ContactInformation
	}
	return nil
}

func (x *CreateAppointmentRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreateAppointmentRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CreateAppointmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type UpdateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppointmentRequest) Reset() {
	*x = UpdateAppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppointmentRequest) ProtoMessage() {}

func (x *UpdateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAppointmentRequest) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

func (x *UpdateAppointmentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAppointmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAppointmentResponse) Reset() {
	*x = DeleteAppointmentResponse{}
	mi := &file_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentResponse) ProtoMessage() {}

func (x *DeleteAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppointmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAppointmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ContactInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactInformation) Reset() {
	*x = ContactInformation{}
	mi := &file_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactInformation) ProtoMessage() {}

func (x *ContactInformation) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactInformation.ProtoReflect.Descriptor instead.
func (*ContactInformation) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *ContactInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactInformation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_appointment_proto protoreflect.FileDescriptor

const file_appointment_proto_rawDesc = "" +
	"\n" +
	"\x11appointment.proto\x12\vappointment\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\xe2\x02\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12P\n" +
	"\x13contact_information\x18\x04 \x01(\v2\x1f.appointment.ContactInformationR\x12contactInformation\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12.\n" +
	"\x04date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"'\n" +
	"\x15GetAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x19GetUserAppointmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x1aGetUserAppointmentResponse\x12<\n" +
	"\fappointments\x18\x01 \x03(\v2\x18.appointment.AppointmentR\fappointments\"\xdf\x02\n" +
	"\x18CreateAppointmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12P\n" +
	"\x13contact_information\x18\x02 \x01(\v2\x1f.appointment.ContactInformationR\x12contactInformation\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12.\n" +
	"\x04date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x93\x01\n" +
	"\x18UpdateAppointmentRequest\x12:\n" +
	"\vappointment\x18\x01 \x01(\v2\x18.appointment.AppointmentR\vappointment\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"*\n" +
	"\x18DeleteAppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteAppointmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\">\n" +
	"\x12ContactInformation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email2\xdc\x03\n" +
	"\x12AppointmentService\x12N\n" +
	"\x0eGetAppointment\x12\".appointment.GetAppointmentRequest\x1a\x18.appointment.Appointment\x12f\n" +
	"\x13GetUserAppointments\x12&.appointment.GetUserAppointmentRequest\x1a'.appointment.GetUserAppointmentResponse\x12T\n" +
	"\x11CreateAppointment\x12%.appointment.CreateAppointmentRequest\x1a\x18.appointment.Appointment\x12T\n" +
	"\x11UpdateAppointment\x12%.appointment.UpdateAppointmentRequest\x1a\x18.appointment.Appointment\x12b\n" +
	"\x11DeleteAppointment\x12%.appointment.DeleteAppointmentRequest\x1a&.appointment.DeleteAppointmentResponseB1Z/github.com/folucode/appointment-scheduler/protob\x06proto3"

var (
	file_appointment_proto_rawDescOnce sync.Once
	file_appointment_proto_rawDescData []byte
)

func file_appointment_proto_rawDescGZIP() []byte {
	file_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)))
	})
	return file_appointment_proto_rawDescData
}

var file_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_appointment_proto_goTypes = []any{
	(*Appointment)(nil),                // 0: appointment.Appointment
	(*GetAppointmentRequest)(nil),      // 1: appointment.GetAppointmentRequest
	(*GetUserAppointmentRequest)(nil),  // 2: appointment.GetUserAppointmentRequest
	(*GetUserAppointmentResponse)(nil), // 3: appointment.GetUserAppointmentResponse
	(*CreateAppointmentRequest)(nil),   // 4: appointment.CreateAppointmentRequest
	(*UpdateAppointmentRequest)(nil),   // 5: appointment.UpdateAppointmentRequest
	(*DeleteAppointmentRequest)(nil),   // 6: appointment.DeleteAppointmentRequest
	(*DeleteAppointmentResponse)(nil),  // 7: appointment.DeleteAppointmentResponse
	(*ContactInformation)(nil),         // 8: appointment.ContactInformation
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),      // 10: google.protobuf.FieldMask
}
var file_appointment_proto_depIdxs = []int32{
	8,  // 0: appointment.Appointment.contact_information:type_name -> appointment.ContactInformation
	9,  // 1: appointment.Appointment.start_time:type_name -> google.protobuf.Timestamp
	9,  // 2: appointment.Appointment.end_time:type_name -> google.protobuf.Timestamp
	9,  // 3: appointment.Appointment.date:type_name -> google.protobuf.Timestamp
	0,  // 4: appointment.GetUserAppointmentResponse.appointments:type_name -> appointment.Appointment
	8,  // 5: appointment.CreateAppointmentRequest.contact_information:type_name -> appointment.ContactInformation
	9,  // 6: appointment.CreateAppointmentRequest.start_time:type_name -> google.protobuf.Timestamp
	9,  // 7: appointment.CreateAppointmentRequest.end_time:type_name -> google.protobuf.Timestamp
	9,  // 8: appointment.CreateAppointmentRequest.date:type_name -> google.protobuf.Timestamp
	0,  // 9: appointment.UpdateAppointmentRequest.appointment:type_name -> appointment.Appointment
	10, // 10: appointment.UpdateAppointmentRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 11: appointment.AppointmentService.GetAppointment:input_type -> appointment.GetAppointmentRequest
	2,  // 12: appointment.AppointmentService.GetUserAppointments:input_type -> appointment.GetUserAppointmentRequest
	4,  // 13: appointment.AppointmentService.CreateAppointment:input_type -> appointment.CreateAppointmentRequest
	5,  // 14: appointment.AppointmentService.UpdateAppointment:input_type -> appointment.UpdateAppointmentRequest
	6,  // 15: appointment.AppointmentService.DeleteAppointment:input_type -> appointment.DeleteAppointmentRequest
	0,  // 16: appointment.AppointmentService.GetAppointment:output_type -> appointment.Appointment
	3,  // 17: appointment.AppointmentService.GetUserAppointments:output_type -> appointment.GetUserAppointmentResponse
	0,  // 18: appointment.AppointmentService.CreateAppointment:output_type -> appointment.Appointment
	0,  // 19: appointment.AppointmentService.UpdateAppointment:output_type -> appointment.Appointment
	7,  // 20: appointment.AppointmentService.DeleteAppointment:output_type -> appointment.DeleteAppointmentResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_appointment_proto_init() }
func file_appointment_proto_init() {
	if File_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_proto_depIdxs,
		MessageInfos:      file_appointment_proto_msgTypes,
	}.Build()
	File_appointment_proto = out.File
	file_appointment_proto_goTypes = nil
	file_appointment_proto_depIdxs = nil
}
